openapi: 3.0.0
info:
  title: Project and Question API
  description: API for managing projects and questions
  version: 1.0.0
tags:
  - name: Projects
    description: Operations related to projects
  - name: Questions
    description: Operations related to questions
  - name: Questionnaires
    description: Operations related to projects questionnaires
paths:

  /questions:
    get:
      summary: Get all questions
      tags: [ Questions ]
      responses:
        200:
          description: The list of all questions

    post:
      summary: Create a new question
      tags: [ Questions ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/Question'
      responses:
        201:
          description: The question was created successfully
        400:
          description: Invalid input
        409:
          description: The question already exists

  /questions/{id}:
    get:
      summary: Get a question
      tags: [ Questions ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the question
      responses:
        200:
          description: The question with the specified ID
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Question'
        400:
          description: Invalid input

    put:
      summary: Update a question
      tags: [ Questions ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/Question'
      responses:
        200:
          description: The question was updated successfully
        400:
          description: The request was invalid

    delete:
      summary: Delete a question
      tags: [ Questions ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the question
      responses:
        200:
          description: The resource was deleted successfully
        400:
          description: The request was invalid

  /projects:
    get:
      summary: Get all projects
      tags: [ Projects ]
      responses:
        200:
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas.yml#/components/schemas/Project"
    post:
      summary: Create a new project
      tags: [ Projects ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/Project'
      responses:
        201:
          description: The resource was created successfully
        400:
          description: The request was invalid
        409:
          description: The project already exists

  /projects/{id}:
    get:
      summary: Get a project
      tags: [ Projects ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the project
      responses:
        200:
          description: The project with the specified ID
          content:
            application/json:
              schema:
                $ref: './schemas.yml#/components/schemas/Project'
        400:
          description: The request was invalid

    put:
      summary: Update a project
      tags: [ Projects ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/Project'
      responses:
        200:
          description: The project was updated successfully
        400:
          description: The request was invalid
        404:
          description: The resource was not found

    delete:
      summary: Delete a project
      tags: [ Projects ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the core
      responses:
        200:
          description: The resource was deleted successfully
        400:
          description: The request was invalid
        404:
          description: The resource was not found

  /projects/{id}/questionnaire:
    get:
      summary: Get all questions filled in by the user for a core
      tags: [ Questionnaires ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the core
      responses:
        200:
          description: The actual list of questions composing the questionnaire of the core

  /projects/{id}/questionnaire/{number}:
    get:
      summary: Get the n-th question of core questionnaire
      tags: [ Questionnaires ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the core
        - in: path
          name: number
          required: true
          schema:
            type: integer
            description: Number of the question
      responses:
        200:
          description: The actual list of questions composing the questionnaire of the core
        400:
          description: The request was invalid

    post:
      summary: Add a new question to the core questionnaire
      tags: [ Questionnaires ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the core
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yml#/components/schemas/Question'
      responses:
        201:
          description: The question was added successfully
        400:
          description: The request was invalid
        409:
          description: The question already exists

    put:
      summary: Update the n-th question of core questionnaire,
        this operation implies the deletion of all successive questions
      tags: [ Questionnaires ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the core
        - in: path
          name: number
          required: true
          schema:
            type: integer
            description: Number of the question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object # TODO: to be defined
      responses:
        200:
          description: The question was updated successfully
        400:
          description: The request was invalid

    delete:
      summary: Delete the n-th question of core questionnaire,
        this operation implies the deletion of all successive questions
      tags: [ Questionnaires ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: ID of the core
        - in: path
          name: number
          required: true
          schema:
            type: integer
            description: Number of the question
      responses:
        200:
          description: The question was deleted successfully
        400:
          description: The request was invalid
        404:
          description: The resource was not found