from pathlib import Path

DIR = Path(__file__).parent

PATH_SKINDESEASES_PREPROCESSING_STABLEDIFF_RES_NONE_CSV = DIR / "results_eor_none.csv"
PATH_SKINDESEASES_PREPROCESSING_STABLEDIFF_RES_MIN_CSV = DIR / "results_eor_augmin.csv"
PATH_SKINDESEASES_PREPROCESSING_STABLEDIFF_RES_BALANCED_CSV = DIR / "results_eor_augbalanced.csv"

PATH_SKINDESEASES_PREPROCESSING_STABLEDIFF_PRED_NONE_CSV = DIR / "predict_none.csv"
PATH_SKINDESEASES_PREPROCESSING_STABLEDIFF_PRED_MIN_CSV = DIR / "predict_augmin.csv"
PATH_SKINDESEASES_PREPROCESSING_STABLEDIFF_PRED_BALANCED_CSV = DIR / "predict_augbalanced.csv"

PATH_SKINDESEASES_PREPROCESSING_STABLEDIFF_POL_PRED_CSV = DIR / "predict_augmax.csv"
