name: Build

on:
  push:
    branches: [ '**' ]

  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    # run on ubuntu, windows and macOS
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install -r requirements.txt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run build
        run: poetry build
      - name: Run tests
        run: poetry run python -m unittest discover -s test

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install -r requirements.txt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Check code style
        run: poetry run black --check .
