name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    concurrency:
      # Only one release job at a time per branch, strictly sequential.
      group: release-${{ github.event.number || github.ref }}
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      
      - name: Install Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test Docker image creation
        run: docker build .

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: 'aequitaseu/backend'
        run: |
          npm install
          npx semantic-release
